"""Pure rendering of the '## Related requirements' block: no file I/O.

Kept separate from :mod:`coherence.mirrors.generate` so the exact text a
dossier's mirror must contain -- given nothing but its ordered SR id list --
is a small, independently testable function with no filesystem or trace-graph
dependency. ``generate.py`` (and ``check``, which is generate's dry-run twin)
both call :func:`render_related_requirements_block` and never construct the
block text any other way, so there is exactly one place the format is
defined.
"""

from __future__ import annotations

from collections.abc import Sequence
import json

from substrate.freshness.fingerprint import sha256_bytes

__all__ = [
    "HEADING",
    "MARKER_LINE",
    "PLACEHOLDER_LINE",
    "fingerprint_requirements",
    "render_related_requirements_block",
]

HEADING = "## Related requirements"

# Human-facing "do not hand-edit" marker (design decision D-P8, item 3).
MARKER_LINE = "<!-- derived — generated by `coherence mirrors generate`; do not edit -->"

# The exact placeholder FEAT-018/019/020 already used for `requirements: []`
# before this generator existed -- the empty state is part of the contract,
# not an absence, and this generator must reproduce it byte-for-byte rather
# than emit an empty section (task brief, "the empty state" section).
PLACEHOLDER_LINE = "- None yet; requirements are pending human-approved authoring."

# All 20 docs/features/FEAT-*.md files use CRLF line endings throughout (no
# bare LF appears in any of them) -- the generated block matches that, byte
# for byte, so regeneration touches only the block's own content, never line
# endings elsewhere in the file (verified with `git diff`, see task report).
_EOL = "\r\n"


def fingerprint_requirements(requirement_ids: Sequence[str]) -> str:
    """Content-hash the canonical, ordered SR id list with the repo's one
    hashing scheme (``substrate.freshness.fingerprint.sha256_bytes``).

    This is what makes the recorded fingerprint independently meaningful: it
    is a function of the *ids and their order*, not of incidental formatting,
    so two dossiers that list the same requirements in the same order always
    fingerprint identically, and any change to membership or order changes
    the digest.
    """
    payload = json.dumps(list(requirement_ids), separators=(",", ":")).encode("utf-8")
    return sha256_bytes(payload)


def _fingerprint_line(requirement_ids: Sequence[str]) -> str:
    return f"<!-- fingerprint: {fingerprint_requirements(requirement_ids)} -->"


def _entry_lines(requirement_ids: Sequence[str]) -> list[str]:
    if not requirement_ids:
        return [PLACEHOLDER_LINE]
    return [f"- [[{req_id}]]" for req_id in requirement_ids]


def render_related_requirements_block(requirement_ids: Sequence[str]) -> str:
    """Render the full section, heading included, ready to append after the
    dossier's own preceding content (which already ends in a newline before
    the heading).

    Deterministic and idempotent by construction: it is a pure function of
    ``requirement_ids`` (the frontmatter's own order, not sorted -- see the
    task report for why sorting would be wrong here), so calling it twice
    with the same input yields byte-identical output every time.
    """
    lines = [
        HEADING,
        "",
        MARKER_LINE,
        _fingerprint_line(requirement_ids),
        *_entry_lines(requirement_ids),
    ]
    return _EOL.join(lines) + _EOL
